require:
  - rubocop-minitest
  - rubocop-rake
  - rubocop-yard
  - rubocop-performance

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  DisplayStyleGuide: true

Performance:
  Exclude:
    - '**/test/**/*'
    - '**/spec/**/*'

Metrics:
  Enabled: false

Layout/LineLength:
  Enabled: false

# Align `end` with the matching keyword or starting expression except for
# assignments, where it should be aligned with the LHS.
Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

# Method definitions after `private` or `protected` isolated calls need one
# extra level of indentation.
Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

Style/FrozenStringLiteralComment:
  EnforcedStyle: always

# Use `foo { bar }` not `foo {bar}`.
Layout/SpaceInsideBlockBraces:
  EnforcedStyleForEmptyBraces: space

# Check quotes usage according to lint rule below.
Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/RedundantReturn:
  AllowMultipleReturnValues: true

Style/Semicolon:
  AllowAsExpressionSeparator: true

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/RescueStandardError:
  EnforcedStyle: implicit

Style/SymbolArray:
  MinSize: 1

Style/DocumentationMethod:
  Enabled: true
  RequireForNonPublicMethods: true

Style/Documentation:
  Enabled: false
